<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Authentications.Domain\Authentications.Domain.csproj" />
    <ProjectReference Include="..\..\..\Common\Common.Domain\Common.Domain.csproj" />
    <ProjectReference Include="..\..\..\Common\Common.Application\Common.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="UseCase\Configutations\" />
    <Folder Include="UseCase\Users\DeleteUsers\" />
    <Folder Include="UseCase\Users\GetAllUsers\" />
    <Folder Include="UseCase\Users\GetUserByEstablishment\" />
    <Folder Include="UseCase\Users\UpdateUsers\" />
  </ItemGroup>
</Project>
