<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Authentications\" />
    <Folder Include="Booking\" />
    <Folder Include="Custommers\" />
    <Folder Include="Reports\" />
    <Folder Include="Notifications\" />
  </ItemGroup>

</Project>
