<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Notifications.Domain\Notifications.Domain.csproj" />
    <ProjectReference Include="..\..\..\Common\Common.Domain\Common.Domain.csproj" />
    <ProjectReference Include="..\..\..\Common\Common.Infrastructure\Common.Infrastructure.csproj" />
  </ItemGroup>
</Project>
