<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Authentications.Application\Authentications.Application.csproj" />
    <ProjectReference Include="..\Authentications.Domain\Authentications.Domain.csproj" />
    <ProjectReference Include="..\..\..\Common\Common.Domain\Common.Domain.csproj" />
    <ProjectReference Include="..\..\..\Common\Common.Infrastructure\Common.Infrastructure.csproj" />
  </ItemGroup>
</Project>
